/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Type__1 = IDL.Variant({
  'coldBrew' : IDL.Null,
  'latte' : IDL.Null,
  'pastries' : IDL.Null,
  'espresso' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : Type__1,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'processing' : IDL.Null,
});
export const ItemQuantity = IDL.Record({
  'itemId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const OrderType = IDL.Record({
  'customerName' : IDL.Text,
  'status' : Type,
  'total' : IDL.Nat,
  'tableNumber' : IDL.Nat,
  'orderId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'discount' : IDL.Nat,
  'items' : IDL.Vec(ItemQuantity),
});
export const BillSummary = IDL.Record({
  'total' : IDL.Nat,
  'orderId' : IDL.Nat,
  'discount' : IDL.Nat,
  'items' : IDL.Vec(ItemQuantity),
  'subtotal' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const SalesReport = IDL.Record({
  'averageOrderValue' : IDL.Nat,
  'dailyRevenue' : IDL.Nat,
  'orderCount' : IDL.Nat,
  'topSellingItems' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItemToOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
  'applyDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
  'getBillSummary' : IDL.Func([IDL.Nat], [IDL.Opt(BillSummary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuEntries' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, MenuItem))], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderType)], ['query']),
  'getSalesReport' : IDL.Func([IDL.Int, IDL.Int], [SalesReport], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeMenuIfEmpty' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, Type], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Type__1 = IDL.Variant({
    'coldBrew' : IDL.Null,
    'latte' : IDL.Null,
    'pastries' : IDL.Null,
    'espresso' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : Type__1,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'processing' : IDL.Null,
  });
  const ItemQuantity = IDL.Record({ 'itemId' : IDL.Nat, 'quantity' : IDL.Nat });
  const OrderType = IDL.Record({
    'customerName' : IDL.Text,
    'status' : Type,
    'total' : IDL.Nat,
    'tableNumber' : IDL.Nat,
    'orderId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'discount' : IDL.Nat,
    'items' : IDL.Vec(ItemQuantity),
  });
  const BillSummary = IDL.Record({
    'total' : IDL.Nat,
    'orderId' : IDL.Nat,
    'discount' : IDL.Nat,
    'items' : IDL.Vec(ItemQuantity),
    'subtotal' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const SalesReport = IDL.Record({
    'averageOrderValue' : IDL.Nat,
    'dailyRevenue' : IDL.Nat,
    'orderCount' : IDL.Nat,
    'topSellingItems' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItemToOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
    'applyDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
    'getBillSummary' : IDL.Func([IDL.Nat], [IDL.Opt(BillSummary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuEntries' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, MenuItem))], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderType)], ['query']),
    'getSalesReport' : IDL.Func([IDL.Int, IDL.Int], [SalesReport], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeMenuIfEmpty' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, Type], [], []),
  });
};

export const init = ({ IDL }) => { return []; };