/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillSummary {
  'total' : bigint,
  'orderId' : bigint,
  'discount' : bigint,
  'items' : Array<ItemQuantity>,
  'subtotal' : bigint,
}
export interface ItemQuantity { 'itemId' : bigint, 'quantity' : bigint }
export interface MenuItem {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : Type__1,
  'price' : bigint,
}
export interface OrderType {
  'customerName' : string,
  'status' : Type,
  'total' : bigint,
  'tableNumber' : bigint,
  'orderId' : bigint,
  'timestamp' : bigint,
  'discount' : bigint,
  'items' : Array<ItemQuantity>,
}
export interface SalesReport {
  'averageOrderValue' : bigint,
  'dailyRevenue' : bigint,
  'orderCount' : bigint,
  'topSellingItems' : Array<[bigint, bigint]>,
}
export type Type = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'processing' : null };
export type Type__1 = { 'coldBrew' : null } |
  { 'latte' : null } |
  { 'pastries' : null } |
  { 'espresso' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItemToOrder' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], bigint>,
  'applyDiscount' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[string, bigint], bigint>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderType>>,
  'getBillSummary' : ActorMethod<[bigint], [] | [BillSummary]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItem' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getOrder' : ActorMethod<[bigint], [] | [OrderType]>,
  'getSalesReport' : ActorMethod<[bigint, bigint], SalesReport>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeMenuIfEmpty' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, Type], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];