/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    name: string;
    description: string;
    available: boolean;
    category: Type__1;
    price: bigint;
}
export interface SalesReport {
    averageOrderValue: bigint;
    dailyRevenue: bigint;
    orderCount: bigint;
    topSellingItems: Array<[bigint, bigint]>;
}
export interface ItemQuantity {
    itemId: bigint;
    quantity: bigint;
}
export interface BillSummary {
    total: bigint;
    orderId: bigint;
    discount: bigint;
    items: Array<ItemQuantity>;
    subtotal: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface OrderType {
    customerName: string;
    status: Type;
    total: bigint;
    tableNumber: bigint;
    orderId: bigint;
    timestamp: bigint;
    discount: bigint;
    items: Array<ItemQuantity>;
}
export enum Type {
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid",
    processing = "processing"
}
export enum Type__1 {
    coldBrew = "coldBrew",
    latte = "latte",
    pastries = "pastries",
    espresso = "espresso"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addItemToOrder(orderId: bigint, itemId: bigint, quantity: bigint): Promise<void>;
    addMenuItem(item: MenuItem): Promise<bigint>;
    applyDiscount(orderId: bigint, discountPercent: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrder(name: string, tableNumber: bigint): Promise<bigint>;
    deleteMenuItem(id: bigint): Promise<void>;
    getAllOrders(): Promise<Array<OrderType>>;
    getBillSummary(orderId: bigint): Promise<BillSummary | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMenu(): Promise<Array<MenuItem>>;
    getMenuItem(id: bigint): Promise<MenuItem | null>;
    getOrder(orderId: bigint): Promise<OrderType | null>;
    getSalesReport(startTime: bigint, endTime: bigint): Promise<SalesReport>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeMenuIfEmpty(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMenuItem(id: bigint, item: MenuItem): Promise<void>;
    updateOrderStatus(orderId: bigint, status: Type): Promise<void>;
}
import type { BillSummary as _BillSummary, ItemQuantity as _ItemQuantity, MenuItem as _MenuItem, OrderType as _OrderType, Type as _Type, Type__1 as _Type__1, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addItemToOrder(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addItemToOrder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItemToOrder(arg0, arg1, arg2);
            return result;
        }
    }
    async addMenuItem(arg0: MenuItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_MenuItem_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_MenuItem_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async applyDiscount(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyDiscount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyDiscount(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrder(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1);
            return result;
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<OrderType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillSummary(arg0: bigint): Promise<BillSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillSummary(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillSummary(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenu(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenu();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenu();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItem(arg0: bigint): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<OrderType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesReport(arg0: bigint, arg1: bigint): Promise<SalesReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesReport(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeMenuIfEmpty(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeMenuIfEmpty();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeMenuIfEmpty();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: bigint, arg1: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItem_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItem_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: Type): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_Type_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_Type_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_MenuItem_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BillSummary]): BillSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : from_candid_MenuItem_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderType]): OrderType | null {
    return value.length === 0 ? null : from_candid_OrderType_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    available: boolean;
    category: _Type__1;
    price: bigint;
}): {
    name: string;
    description: string;
    available: boolean;
    category: Type__1;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        available: value.available,
        category: from_candid_Type__1_n19(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _Type;
    total: bigint;
    tableNumber: bigint;
    orderId: bigint;
    timestamp: bigint;
    discount: bigint;
    items: Array<_ItemQuantity>;
}): {
    customerName: string;
    status: Type;
    total: bigint;
    tableNumber: bigint;
    orderId: bigint;
    timestamp: bigint;
    discount: bigint;
    items: Array<ItemQuantity>;
} {
    return {
        customerName: value.customerName,
        status: from_candid_Type_n10(_uploadFile, _downloadFile, value.status),
        total: value.total,
        tableNumber: value.tableNumber,
        orderId: value.orderId,
        timestamp: value.timestamp,
        discount: value.discount,
        items: value.items
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    processing: null;
}): Type {
    return "cancelled" in value ? Type.cancelled : "pending" in value ? Type.pending : "paid" in value ? Type.paid : "processing" in value ? Type.processing : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coldBrew: null;
} | {
    latte: null;
} | {
    pastries: null;
} | {
    espresso: null;
}): Type__1 {
    return "coldBrew" in value ? Type__1.coldBrew : "latte" in value ? Type__1.latte : "pastries" in value ? Type__1.pastries : "espresso" in value ? Type__1.espresso : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderType>): Array<OrderType> {
    return value.map((x)=>from_candid_OrderType_n8(_uploadFile, _downloadFile, x));
}
function to_candid_MenuItem_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Type__1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    available: boolean;
    category: Type__1;
    price: bigint;
}): {
    name: string;
    description: string;
    available: boolean;
    category: _Type__1;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        available: value.available,
        category: to_candid_Type__1_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    processing: null;
} {
    return value == Type.cancelled ? {
        cancelled: null
    } : value == Type.pending ? {
        pending: null
    } : value == Type.paid ? {
        paid: null
    } : value == Type.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    coldBrew: null;
} | {
    latte: null;
} | {
    pastries: null;
} | {
    espresso: null;
} {
    return value == Type__1.coldBrew ? {
        coldBrew: null
    } : value == Type__1.latte ? {
        latte: null
    } : value == Type__1.pastries ? {
        pastries: null
    } : value == Type__1.espresso ? {
        espresso: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
